spring.application.name=reservationapi

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3307/roomdb
spring.datasource.username=roomdbuser
spring.datasource.password=roomdbuser

spring.jooq.sql-dialect=org.hibernate.dialect.MariaDBDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5